import Head from "next/head";
import Image from "next/image";
import TeamsList from "../../components/TeamsList";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Matches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TeamsList />
    </div>
  );
}